---
server:
  port: 8888

spring:
  application:
    name: config-service
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/smitchell/[Your repo repository name]
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          search-paths: {application}
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: '*'


